import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

export default new Vuex.Store({
  state: {
      phone:window.localStorage.getItem('phone'),
      haslogin:window.localStorage.getItem('haslogin'),
      chineseData: {
        netWorkTitle: "全网有效数据",
        newWorkFenDataCap: "全网已分配DataCap",
        newWorkShiDataCap: "全网已释放DataCap",
        newWorkYongDataCap: "全网已使用DataCap",
        newWorkFenDataCap1: "全网已分配DataCap：",
        newWorkShiDataCap2: "全网已释放DataCap：",
        newWorkYongDataCap3: "全网已使用DataCap：",
        timeDate: "选择时间范围",
        export: "导出",
        upTime: "数据更新时间：",
        newWorkDate: "日期",
        newWorkTotalNotary: "全网已分配DataCap",
        newWorkPlusNotary: "全网Plus已分配",
        newWorkLNDNotary: "全网LDN已分配",
        newWorkTotalClient: "全网已释放DataCap",
        newWorkPlusClient: "全网Plus已释放",
        newWorkLNDClient: "全网LDN已释放",
        newWorkTotalDC: "全网已使用DataCap",
        newWorkNewNotary: "新增已分配DataCap",
        newWorkNewPlusNotary: "Plus新增已分配",
        newWorkNewLDNNotary: "LDN新增已分配",
        newWorkNewClient: "新增已释放DataCap",
        newWorkNewPlusClient: "Plus新增已释放",
        newWorkNewLDNClient: "LDN新增已释放",
        newWorkNewlDC: "新增已使用DataCap",
        notoryTitle: "有效数据-Notary",
        notoryInput: "Notary地址",
        rank: "排名",
        notoryClientAddress: "Notary",
        notoryDCNotroy: "已分配DataCap",
        notoryDCClient: "已释放DataCap",
        notoryUserDC: "已使用DataCap",
        notoryDCRemain: "未使用DataCap",
        action: "操作",
        check: "查看",
        noData: "暂无数据...",
        loading: "加载中",
        status:"状态",
        clientTitle: "有效数据-Client",
        clientInput: "Client地址",
        clientAdress: "Client",
        clientToNotroy: "已分配DataCap",
        clientToNotroyPlus: "Plus已分配",
        clientToNotroyLND: "LDN已分配",
        clientToClient: "已释放DataCap",
        clientToClientPlus: "Plus已释放",
        clientToClientLND: "LDN已释放",
        clientToUsedDC: "已使用DataCap",
        clientDCRemain: "未使用DataCap",
        minerTitle: "有效数据-Miner",
        minerInput: "Miner地址",
        minerAddress: "Miner地址",
        minerClientAddress: "Client数量",
        minerAdujusted:"有效算力",
        minerSealedDC: "已封装DataCap",
        clientDetailTitle: "Client详情",
        clientDetailToNotroy: "已分配DataCap",
        clientDetailToClient: "已释放DataCap",
        clientDetailToUsedDC: "已使用DataCap",
        clientDetailToDCRemain: "未使用DataCap",
        clientDetailUserList: "Client已使用详情",
        clientDetailInput:"Miner地址",
        clientDetailSPID: "Miner地址",
        clientDetailDataCap: "DataCap",
        clientDetailDeal: "Deal数量",
        clientDetailFail:"失败数量",
        clientDetailDealTitle: "Deal详情",
        clientDetailDealStatus: "全部状态",
        clientDetailDealCid: "消息ID",
        clientDetailDealId: "交易ID",
        clientDetailDealClient: "Client",
        clientDetailDealProvider: "Miner",
        clientDetailDealPieceSize: "PieceSize",
        clientDetailDealCreatTime: "创建时间",
        clientDetailDealStartTime: "开始时间",
        clientDetailDealEndTime: "结束时间",
        clientDetailDealEpochPrice: "存储费用(FIL)",
        minerDetailTitle: "Miner详情",
        minerDetailSealedDC: "已封装DataCap",
        minerDetailSourceList: "DataCap来源列表",
        minerDetailInput: "Client地址",
        minerDetailAddress: "来源Client",
        minerDetailDataCap: "DataCap",
        minerDetailDealnumbers: "Deal数量",
        minerDetailFailnumbers: "失败数量",
        minerDetailDealDetail: "Deal详情",
        minerDetailDealProposalCID: "消息ID",
        minerDetailDealID: "交易ID",
        minerDetailDealClient: "Client",
        minerDetailDealProvider: "Miner",
        minerDetailDealPieceSize: "PieceSize",
        minerDetailDealCreateTime: "创建时间",
        minerDetailDeaStartTime: "开始时间 ",
        minerDetailDeaEndTime : "结束时间 ",
        minerDetailDealEpochPrice: "存储费用(Fil)",
        notoryDetailTitle: "Notary详情",
        notoryDetailToNotroy: "已分配DataCap",
        notoryDetailToClient: "已释放DataCap",
        notoryDetailToUsed: "已使用DataCap",
        notoryDetailToRemain: "未使用DataCap",
        notoryDetailUsedList: "Notary使用详情",
        notoryDetailAddress: "Client地址",
        notoryDetailClient: "Client",
        notoryDetailDataCap: "DataCap",
        notoryDetailDealnumbers: "次数",
        notoryDetailFailnumbers: "失败数量",
        notoryDetailMassageTitle: "消息详情",
        notoryDetailMassageID: "消息ID",
        notoryDetailMassageClient: "Client",
        notoryDetailMassageDataCap: "DataCap",
        notoryDetailMassageTime:"时间",
      },
      englishData: {
        netWorkTitle: "DataCap Overview",
        newWorkFenDataCap: "Total DC to Notary",
        newWorkShiDataCap: "Total DC to Client",
        newWorkYongDataCap: "Total Used DC",
        newWorkFenDataCap1: "Total DC to Notary:",
        newWorkShiDataCap2: "Total DC to Client:",
        newWorkYongDataCap3: "Total Used DC:",
        timeDate: "Please select time",
        export: "Export",
        upTime: "Update Time:",
        newWorkDate: "Date",
        newWorkTotalNotary: "Total DC to Notary",
        newWorkPlusNotary: "FIL+ to Notary",
        newWorkLNDNotary: "LDN to Notary",
        newWorkTotalClient: "Total DC to Client",
        newWorkPlusClient: "FIL+ to Client",
        newWorkLNDClient: "LDN to Client",
        newWorkTotalDC: "Total Used DC",
        newWorkNewNotary: "New DC to Notary",
        newWorkNewPlusNotary: "New FIL+ to Notary",
        newWorkNewLDNNotary: "New LDN to Notary",
        newWorkNewClient: "New DC to Client",
        newWorkNewPlusClient: "New FIL+ to Client",
        newWorkNewLDNClient: "New LDN to Client",
        newWorkNewlDC: "New Used DC",
        notoryTitle: "Notary",
        notoryInput: "Notary Address",
        rank: "Ranking",
        notoryClientAddress: "Notary Address",
        notoryDCNotroy: "FIL+ to Notary",
        notoryDCClient: "DC to Client",
        notoryUserDC: "Notary to Client",
        notoryDCRemain: "DC Unallocated",
        action: "action",
        check: "more",
        noData: "No data yet...",
        loading: "loading",
        status:"status",
        clientTitle: "Client",
        clientInput: "Client Address",
        clientAdress: "Client Address",
        clientToNotroy: "DC to Client",
        clientToNotroyPlus: "FIL+ to Client",
        clientToNotroyLND: "LDN to Client",
        clientToClient: "DC Allocated",
        clientToClientPlus: "FIL+ to Client",
        clientToClientLND: "LDN to Client",
        clientToUsedDC: "Used DC",
        clientDCRemain: "Unused DC",
        minerTitle: "Storage Provider",
        minerInput: "SP ID",
        minerAddress: "SP ID",
        minerClientAddress: "Client Address",
        minerAdujusted:"Adjusted Power",
        minerSealedDC: "Sealed DC",
        clientDetailTitle: "Client Detail",
        clientDetailToNotroy: "DC to Notary",
        clientDetailToClient: "DC to Client",
        clientDetailToUsedDC: "Used DC",
        clientDetailToDCRemain: "DC Remain",
        clientDetailUserList: "Client Used List",
        clientDetailInput:"SP ID",
        clientDetailSPID: "SP ID",
        clientDetailDataCap: "DataCap",
        clientDetailDeal: "Deal numbers",
        clientDetailFail:"Fail numbers",
        clientDetailDealTitle: "Deal Detail",
        clientDetailDealStatus: "ALL",
        clientDetailDealCid: "Proposal CID",
        clientDetailDealId: "Deal ID",
        clientDetailDealClient: "Client",
        clientDetailDealProvider: "Provider",
        clientDetailDealPieceSize: "PieceSize",
        clientDetailDealCreatTime: "Create Time",
        clientDetailDealStartTime: "StartTime",
        clientDetailDealEndTime: "EndTime",
        clientDetailDealEpochPrice: "Epoch Price",
        minerDetailTitle: "Provider Detail",
        minerDetailSealedDC: "Sealed DC",
        minerDetailSourceList: "Source List",
        minerDetailInput: "Client Address",
        minerDetailAddress: "Client",
        minerDetailDataCap: "DataCap",
        minerDetailDealnumbers: "Deal numbers",
        minerDetailFailnumbers: "Fail numbers",
        minerDetailDealDetail: "Deal Detail",
        minerDetailDealProposalCID: "Proposal CID",
        minerDetailDealID: "Deal ID",
        minerDetailDealClient: "Client",
        minerDetailDealProvider: "Provider",
        minerDetailDealPieceSize: "PieceSize",
        minerDetailDealCreateTime: "Create Time",
        minerDetailDeaStartTime: "StartTime ",
        minerDetailDeaEndTime : "EndTime ",
        minerDetailDealEpochPrice: "Epoch Price",
        notoryDetailTitle: "Notary Detail",
        notoryDetailToNotroy: "FIL+ to Notary",
        notoryDetailToClient: "DC to Client",
        notoryDetailToUsed: "Notary to Client",
        notoryDetailToRemain: "DC Unallocated",
        notoryDetailUsedList: "Used List",
        notoryDetailAddress: "Client address",
        notoryDetailClient: "Client",
        notoryDetailDataCap: "Client",
        notoryDetailDealnumbers: "numbers",
        notoryDetailFailnumbers: "Fail numbers",
        notoryDetailMassageTitle: "Massage Detail",
        notoryDetailMassageID: "Massage ID",
        notoryDetailMassageClient: "Client",
        notoryDetailMassageDataCap: "DataCap",
        notoryDetailMassageTime:"Time",
      }
  },
  mutations: {
      setphone:(state,data)=>{
          state.phone =data;
          window.localStorage.setItem('phone',data)
      },
      sethaslogin:(state,data)=>{
        state.haslogin =data;
        window.localStorage.setItem('haslogin',data)
    },
    loginout:(state)=>{
        state.phone ='';
        state.haslogin = false,
        localStorage.setItem("phone", '');
        localStorage.setItem("haslogin", '');
    }
  },
  actions: {
  },
  modules: {
  }
})
